### ISSUE TITLE
Plugin "services" throws a TypeError with SYSTEM Hive

### ISSUE THREAD

**Issue by wagga40** [mkorman90/regipy#68]
When using the plugin "services" on the SYSTEM Hive, Python 3.7 is throwing a TypeError.

```sh
$ registry-plugins-run SYSTEM -p services -o out.json                                                                                          
Loaded 17 plugins
[2020-04-08 21:16:03.152736] INFO: regipy.plugins.system.services: Started Services enumeration Plugin...
[2020-04-08 21:16:03.154465] INFO: regipy.registry: Found control sets: ['\\ControlSet001\\Services']
Traceback (most recent call last):
  File "/usr/local/bin/registry-plugins-run", line 10, in <module>
    sys.exit(run_plugins())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/regipy/cli.py", line 107, in run_plugins
    plugin_results = run_relevant_plugins(registry_hive, as_json=True, plugins=plugins)
  File "/usr/local/lib/python3.7/site-packages/regipy/plugins/utils.py", line 21, in run_relevant_plugins
    plugin.run()
  File "/usr/local/lib/python3.7/site-packages/regipy/plugins/system/services.py", line 29, in run
    'timestamp': subkey.header.last_modified
TypeError: list indices must be integers or slices, not str
```

**Comment by wagga40** [comment]
Corrected in master (but not in Pypi version) as of today. Sorry for the noise. Closing issue.
