### ISSUE TITLE
Encoding issue in PowerShell ISE and Visual Studio Code

### ISSUE THREAD

**Issue by evild3ad** [mkorman90/regipy#95]
Following command works in Windows PowerShell and Windows Terminal:
registry-parse-header HIVE_PATH

The same command is not working in PowerShell ISE and Visual Studio Code:
registry-parse-header : Traceback (most recent call last):
In Zeile:1 Zeichen:1
+ registry-parse-header "C:\Users\evild3ad\Desktop\Artifacts-Collector\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "C:\Program Files\Python37\Scripts\registry-parse-header-script.py", line 11, in <module>
    load_entry_point('regipy==1.6.3', 'console_scripts', 'registry-parse-header')()
  File "C:\Program Files\Python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\regipy\cli.py", line 30, in parse_header
    click.secho(tabulate(registry_hive.header.items(), tablefmt='fancy_grid'))
  File "C:\Program Files\Python37\lib\site-packages\click\termui.py", line 548, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
  File "C:\Program Files\Python37\lib\site-packages\click\utils.py", line 272, in echo
    file.write(message)
  File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-59: character maps to <undefined>

I tried to fix the encoding issue in Visual Studio Code without success. Any tips for me?

My file encoding is UTF-8 with BOM.

Thank you!

**Comment by tincho9** [comment]
It fails on a specific registry hive, or on any hive?

**Comment by evild3ad** [comment]
It fails on any hive in Powershell ISE and Visual Studio Code. I expect you can change the encoding settings in Visual Studio Code...but it is still not working for me. I like the splitted view (Code and Terminal) in these two apps.

**Comment by tincho9** [comment]
![image](https://user-images.githubusercontent.com/18242935/93012438-1ba07480-f5a9-11ea-832a-757ae3698905.png)
This is the output of parse header... The only possible issue would be related to the `b'regf'` signature... Can you try modifying it in your code just to see if that is the issue? It'll take me some time to recreate your environment.

**Comment by tincho9** [comment]
Did you try it?

**Comment by tincho9** [comment]
Let me know if this is still relevant.
